name: Probot Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  probot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run Probot
        run: npx probot run ./index.js
