name: Scheduled Task

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every day at midnight

jobs:
  run-probot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run Probot
        run: npx probot run ./index.js
